kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-test
spec:
  replicas: 500
  minReadySeconds: 5
  selector:
    matchLabels:
      app: client-test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client-test
    spec:
      containers:
        - name: iliks-client
          image: iliks-client:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 0.1
              memory: 200Mi
          env:
            - name: SERVER_ADDR
              value: server-svc
