kind: Deployment
apiVersion: apps/v1
metadata:
  name: client-test
spec:
  replicas: 20
  minReadySeconds: 5
  selector:
    matchLabels:
      app: client-test
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client-test
    spec:
      containers:
        - name: iliks-client
          image: iliks-client:5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 120Mi
          env:
            - name: SERVER_ADDR
              value: "http://server-svc1:8080/api/"
