include:
  - infra.yaml
services:
  srv:
    image: "iliks-server:7"
    secrets:
    #appears in /run/secrets/my_secret
      - my_secret
    ports:
      - target: 8080
        published: 81
    cpus: 0.1
#note: client will give a lot of initial errors,
#because server is slow to start, can set up health check...
  clnt:
    image: "iliks-client:5"
    depends_on:
      - srv
    environment:
      - SERVER_ADDR=http://srv:8080/api/
      - A
    cpus: 0.1
secrets:
  my_secret:
    file: secret.txt