services:
  srv:
    image: "iliks-server:7"
    networks:
      - net
    ports:
      - target: 8080
        published: 81
    cpus: 0.1
#note: client will give a lot of initial errors,
#because server is slow to start
  clnt:
    image: "iliks-client:5"
    depends_on:
      - srv
    networks:
      - net
    environment:
      SERVER_ADDR: http://srv:8080/api/
    cpus: 0.1
  prometheus:
    image: "prom/prometheus:latest"
    depends_on:
      - srv
    networks:
      - net
    ports:
      - "82:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_vol:/prometheus
networks:
  net:
volumes:
  prometheus_vol: