management:
    endpoints:
        web.exposure.include: health,prometheus
    endpoint:
        health:
            show-details: always
            show-components: always
#explicitly enabling to be able to test not only under k8s
    health:
        livenessstate.enabled: true
        readinessstate.enabled: true