#this file is just to play with secrets.
#I do realise it's a bad practice to create a secret in yaml.
kind: Pod
apiVersion: v1 #from kubectl api-resources
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: test-secret-volume
          mountPath: /tmp/secrets
  volumes:
      - name: test-secret-volume
        projected:
          defaultMode: 420
          sources:
            - secret:
                name: test-secret

---
kind: Secret
apiVersion: v1
metadata:
  name: test-secret
stringData:
  #try modifying after creating and watch the projected volume change in pod without pod restart -
  #by default it takes about a minute to apply!
  "test.pwd": |
    pwd1=password1.2
    pwd2=password2.2
    pwd3=password3.2