/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cloud.test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ClientTest {
    @Test void appHasAGreeting() {
        Client classUnderTest = new Client();
    }
}
