/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cloud.test;

import org.springframework.boot.WebApplicationType;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;

@SpringBootApplication
public class Client {

    public static void main(String[] args) {
        new SpringApplicationBuilder(Client.class)
                .web(WebApplicationType.NONE)
                .run(args);
    }
}
